MAMS/Models/ViewModels/AvailabilityViewModel.cs
using static MAMS.Services.Enums;

namespace MAMS.Models.ViewModels
{
    public class AvailabilityViewModel
    {

        public Days Available_Day { get; set; }
        public TimeSpan? StartTime { get; set; }
        public TimeSpan? EndTime { get; set; }
        public ActiveStatus ActiveStatus { get; set; }
    }
}

MAMS/Controllers/AvailabilityController.cs
using AspNetCoreHero.ToastNotification.Abstractions;
using MAMS.Models;
using MAMS.Services;
using Microsoft.AspNetCore.Mvc;

namespace MAMS.Controllers
{
    public class AvailabilityController : BaseController
    {
        private readonly ILogger<DoctorController> _logger;

        public AvailabilityController(IConfiguration config, INotyfService notfy, ILogger<DoctorController> logger, IHttpContextAccessor contextAccessor, AppSettings appSettings)
            : base(config, notfy, contextAccessor, appSettings)
        {
            _logger = logger;
        }

        public async Task<IActionResult> Index(int id)
        {
            IEnumerable<DoctorAvailableDetails> availabilities = new List<DoctorAvailableDetails>();

            if (!IsSessionValid())
            {
                return View("TimedOut", "Home");
            }

            try
            {
                var result = await _availabilityService.AvailabilityAsync(id);

                if (result.Item1 != null)
                {
                    availabilities = result.Item1;
                }
                else
                {
                    _notfy.Error(result.Item2);
                    return View();
                }

                ViewData.Model = availabilities;
                ViewData["DoctorId"] = id;
            }
            catch (Exception ex)
            {
                ModelState.AddModelError(string.Empty, $"Error: {ex.Message}");
                _notfy.Warning($"{ex.Message}", 5);
            }
            return View();
        }

        public async Task<IActionResult> Update(DoctorAvailableDetails doctorAvailableDetails)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    (bool success, string errorMessage) = await _availabilityService.UpdateAvailabilityAsync(doctorAvailableDetails);

                    if (success)
                    {
                        _notfy.Success($"{doctorAvailableDetails.Available_Day}, Updated successfully.");
                        //return View("Index");
                    }
                    else
                    {
                        _notfy.Warning(errorMessage);
                        _notfy.Error("update Fail!.", 5);
                    }
                }
            }
            catch (Exception ex)
            {
                ModelState.AddModelError(string.Empty, $"Error: {ex.Message}");
                _notfy.Error($"Error calling web API: {ex.Message}", 5);
            }

            ViewData["DoctorId"] = doctorAvailableDetails.DoctorId;
            var availabilities = await _availabilityService.AvailabilityAsync(doctorAvailableDetails.DoctorId);
            return View("Index", availabilities.Item1 ?? new List<DoctorAvailableDetails>());
        }

        public async Task<IActionResult> AddNew(DoctorAvailableDetails newAvailability)
        {

            DoctorAvailableDetails doctorAvailableDetails = new DoctorAvailableDetails()
            {
                DoctorId = newAvailability.DoctorId,
                Available_Day = newAvailability.Available_Day,
                StartTime = newAvailability.StartTime,
                EndTime = newAvailability.EndTime
            };



            try
            {

                if (ModelState.IsValid && newAvailability.DoctorId > 0)
                {
                    (bool success, string errorMessage) = await _availabilityService.AddAvailabilityAsync(doctorAvailableDetails);

                    if (success)
                    {
                        _notfy.Success("Availability Added Successfully!.");
                    }
                    else
                    {
                        _notfy.Error("Adding Fail!", 5);
                        _notfy.Warning(errorMessage);
                        ModelState.AddModelError(string.Empty, errorMessage);
                    }
                }
                else
                {
                    _notfy.Error("Invalid model state or invalid Doctor ID.");
                }

            }
            catch (Exception ex)
            {
                _notfy.Error($"Error calling web API: {ex.Message}", 5);
            }
            ViewData["DoctorId"] = doctorAvailableDetails.DoctorId;
            var availabilities = await _availabilityService.AvailabilityAsync(doctorAvailableDetails.DoctorId);
            return View("Index", availabilities.Item1 ?? new List<DoctorAvailableDetails>());
        }

        public async Task<IActionResult> Delete(int id, int doctorId)
        {
            if (!IsSessionValid())
            {
                return View("TimedOut", "Home");
            }

            try
            {
                if (doctorId > 0)
                {
                    var result = await _availabilityService.DeleteAvailabilityAsync(id);

                    if (result.success)
                    {
                        _notfy.Success("Delete Successfully!");
                    }
                    else
                    {
                        _notfy.Warning(result.ErrorMessage);
                    }
                }
                else
                {
                    _notfy.Error("Doctor Id required!. Please Contact your Admin.", 5);
                }
            }
            catch (Exception ex)
            {
                _notfy.Error($"Error calling web API: {ex.Message}", 5);
            }

            ViewData["DoctorId"] = doctorId;
            var availabilities = await _availabilityService.AvailabilityAsync(doctorId);
            return View("Index", availabilities.Item1 ?? new List<DoctorAvailableDetails>());

        }
    }
}

MAMS/Views/Availability/Index.cshtml
@using System.Data
@using MAMS.Services
@using MAMS.Models

@{
    ViewData["Title"] = "Availabilities";
    var doctorId = ViewData["DoctorId"] as int?;
}

@model IEnumerable<DoctorAvailableDetails>

<!-- DataTables -->
<link rel="stylesheet" href="~/adminlte/plugins/datatables-bs4/css/dataTables.bootstrap4.min.css">
<link rel="stylesheet" href="~/adminlte/plugins/datatables-responsive/css/responsive.bootstrap4.min.css">
<link rel="stylesheet" href="~/adminlte/plugins/datatables-buttons/css/buttons.bootstrap4.min.css">

<div class="container">
    <div class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-12 d-flex justify-content-between align-items-center">
                    <h1>Availabilities</h1>
                    <a asp-controller="Doctor" asp-action="Index" class="btn bg-gradient-secondary rounded-pill float-right" style="width:150px"><i class="bi bi-backspace"></i> &nbsp; Back</a>
                </div>
                <div class="col-sm-12">
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item"><a asp-action="Index">Doctors</a></li>
                        <li class="breadcrumb-item active">All Availabilities</li>
                    </ol>
                </div>
            </div><!-- /.row -->
        </div><!-- /.container-fluid -->
    </div>

    <div class="content">
        <div class="row">
            <div class="col-12">
                <div class="card card-info card-outline">
                    <div class="card-header card-header d-flex justify-content-between align-items-center">
                        @* <form method="get" asp-controller="Availability" asp-action="Index" class="d-flex ml-auto">
                            <div class="input-group input-group-sm" style="width: 250px;">
                                <input type="text" name="searchString" class="form-control float-left" placeholder="Search by Day or Time" value="@ViewData["CurrentFilter"]">
                                <div class="input-group-append">
                                    <button type="submit" class="btn btn-default">
                                        <i class="fas fa-search"></i>
                                    </button>
                                </div>
                            </div>
                        </form> *@
                    </div>
                    <!-- /.card-header -->

                    <div class="card-body table-responsive p-0">

                        @if (Model == null)
                        {
                            <div class="alert alert-danger" role="alert">
                                Error: Failed to load data. Please try again later. or Please Log in again.
                            </div>
                        }
                        else if (!Model.Any())
                        {
                            <div class="alert alert-warning" role="alert">
                                NO Availability Found!
                            </div>
                        }

                        else
                        {
                            <table id="Availability" class="table table-hover">
                                <thead>
                                    <tr>
                                        <th>Available Day</th>
                                        <th>From</th>
                                        <th>To</th>
                                        <th>Status</th>
                                        <th class="text-center">Actions</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach (var obj in Model)
                                    {
                                        <tr>
                                            <input asp-for="@obj.Id" hidden />
                                            <input asp-for="@obj.DoctorId" hidden />
                                            <td data-Available_day="@obj.Available_Day">@obj.Available_Day</td>
                                            <td class="text-start">@(obj.StartTime.HasValue ? new DateTime(obj.StartTime.Value.Ticks).ToString("hh:mm tt") : "")</td>
                                            <td class="text-Start">@(obj.EndTime.HasValue ? new DateTime(obj.EndTime.Value.Ticks).ToString("hh:mm tt") : "")</td>
                                            <td>
                                                @if (obj.ActiveStatus == Enums.ActiveStatus.Active)
                                                {
                                                    <span class="badge bg-gradient-success">Active</span>
                                                }
                                                else if (obj.ActiveStatus == Enums.ActiveStatus.Inactive)
                                                {
                                                    <span class="badge bg-gradient-danger">Inactive</span>
                                                }
                                            </td>

                                            <td class ="text-center">
                                                <div class="btn-group btn-group-justified" role="group">
                                                    <button type="button" class="btn btn-light" data-bs-toggle="modal" data-bs-target="#editModal-@obj.Id" title="Edit">
                                                        <i class="bi bi-pencil-square"></i>
                                                    </button>
                                                    <button type="button" class="delete-button btn btn-light" data-id="@obj.Id" data-doctor-id="@obj.DoctorId" title="Delete">
                                                        <i class="bi bi-trash3-fill"></i>
                                                    </button>
                                                </div>
                                            </td>
                                        </tr>

                                        @await Html.PartialAsync("_EditAvailability", obj)

                                    }
                                </tbody>
                            </table>

                        }

                    </div>
                    <!-- /.card-body -->

                    <div class="card-footer">
                        <button type="button" class="btn bg-gradient-success rounded-pill float-right" data-bs-toggle="modal" data-bs-target="#addNewModal" data-doctor-id="@doctorId" style="width:150px">
                            <i class="bi bi-plus-circle"></i>&ensp; Add New
                        </button>
                    </div>
                </div>
                <!-- /.card -->
            </div>
        </div>
    </div>
</div>

<div class="modal fade" id="deleteConfirmationModal" tabindex="-1" role="dialog" aria-labelledby="showDeleteConfirmationModal" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-body">
                Are you sure you want to Delete this Day?
            </div>
            <div class="modal-footer">
                <button type="button" class="btn bg-gradient-secondary" data-bs-dismiss="modal">No</button>
                <button type="button" class="btn bg-gradient-danger" id="confirmYes">Delete</button>
            </div>
        </div>
    </div>
</div>

@await Html.PartialAsync("_AddAvailability", new DoctorAvailableDetails())

<!-- DataTables  & Plugins -->
<script src="~/adminlte/plugins/datatables/jquery.dataTables.min.js"></script>
<script src="~/adminlte/plugins/datatables-bs4/js/dataTables.bootstrap4.min.js"></script>
<script src="~/adminlte/plugins/datatables-responsive/js/dataTables.responsive.min.js"></script>
<script src="~/adminlte/plugins/datatables-responsive/js/responsive.bootstrap4.min.js"></script>
<script src="~/adminlte/plugins/datatables-buttons/js/dataTables.buttons.min.js"></script>
<script src="~/adminlte/plugins/datatables-buttons/js/buttons.bootstrap4.min.js"></script>
<script src="~/adminlte/plugins/jszip/jszip.min.js"></script>
<script src="~/adminlte/plugins/pdfmake/pdfmake.min.js"></script>
<script src="~/adminlte/plugins/pdfmake/vfs_fonts.js"></script>
<script src="~/adminlte/plugins/datatables-buttons/js/buttons.html5.min.js"></script>
<script src="~/adminlte/plugins/datatables-buttons/js/buttons.print.min.js"></script>
<script src="~/adminlte/plugins/datatables-buttons/js/buttons.colVis.min.js"></script>

@section Scripts {
    <script>
        function showDeleteConfirmationModal(id, doctorId) {
            $('#confirmYes').data('id', id).data('doctor-id', doctorId);
            $('#deleteConfirmationModal').modal('show');
        }

        $(document).ready(function () {

            $('.delete-button').click(function () {
                var id = $(this).data('id');
                var doctorId = $(this).data('doctor-id');
                console.log("1Confirm clicked - ID:", id, "1Doctor ID:", doctorId);
                showDeleteConfirmationModal(id, doctorId);
            });

            $('#confirmYes').click(function () {
                var id = $(this).data('id');
                var doctorId = $(this).data('doctor-id');
                $('#deleteConfirmationModal').modal('hide');
                console.log("Confirm clicked - ID:", id, "Doctor ID:", doctorId);
                window.location.href = '@Url.Action("Delete", "Availability")' + '?id=' + id + '&doctorId=' + doctorId;
            });

            $("#Availability").DataTable({
                    "responsive": true,
                    "lengthChange": false,
                    "autoWidth": false,
                    "ordering": true,
                    "paging": true,
                    "info": true,
                    "searching": true,
                    "buttons": ["copy", "csv", "excel", "pdf", "print", "colvis"]
                }).buttons().container().appendTo('#Availability_wrapper .col-md-6:eq(0)');
        });

        
    </script>
}

MAMS/Views/Availability/_AddAvailability.cshtml
@using static MAMS.Services.Enums

@model DoctorAvailableDetails

<!-- Add New Modal -->
<div class="modal fade" id="addNewModal" tabindex="-1" aria-labelledby="addNewModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header bg-success">
                <h5 class="modal-title" id="addNewModalLabel">Add New Availability</h5>
                <button type="button" class="close" data-bs-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <form method="post" asp-action="AddNew" asp-controller="Availability" asp-route-id="@Model.Id">
                    <input type="hidden" value="@ViewData["DoctorId"]" asp-for="DoctorId" />
                    <div class="form-group">
                        <label asp-for="Available_Day">Available Day</label>
                        <select asp-for="Available_Day" class="form-control">
                            <option value="">--Day--</option>
                            @foreach (var day in Enum.GetValues(typeof(Days)))
                            {
                                <option value="@day">@day</option>
                            }
                        </select>
                    </div>
                    <div class="form-group">
                        <label asp-for="StartTime">From</label>
                        <input type="time" asp-for="StartTime" class="form-control" />
                    </div>
                    <div class="form-group">
                        <label asp-for="EndTime">To</label>
                        <input type="time" asp-for="EndTime" class="form-control" />
                    </div>
                    <div class="modal-footer">
                        <button type="submit" class="btn bg-gradient-success">Add</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

MAMS/Views/Availability/_EditAvailability.cshtml
@using static MAMS.Services.Enums

@model MAMS.Models.DoctorAvailableDetails

<!-- Edit Modal -->
<div class="modal fade" id="editModal-@Model.Id" tabindex="-1" role="dialog" aria-labelledby="editModalLabel-@Model.Id" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header bg-info">
                <h5 class="modal-title" id="editModalLabel-@Model.Id">Edit Availability</h5>
                <button type="button" class="close" data-bs-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <form asp-action="Update" asp-controller="Availability" method="post">
                    <input type="hidden" asp-for="@Model.Id" value="@Model.Id" />
                    <input type="hidden" asp-for="@Model.DoctorId" value="@Model.DoctorId" />
                    <div class="form-group">
                        <label asp-for="@Model.Available_Day">Available Day</label>
                        <select asp-for="@Model.Available_Day" class="form-control">
                            <option value="">--Day--</option>
                            @foreach (var day in Enum.GetValues(typeof(Days)))
                            {
                                <option value="@day">@day</option>
                            }
                        </select>
                    </div>
                    <div class="form-group">
                        <label asp-for="@Model.StartTime">From</label>
                        <input type="time" asp-for="@Model.StartTime" class="form-control" />
                    </div>
                    <div class="form-group">
                        <label asp-for="@Model.EndTime">To</label>
                        <input type="time" asp-for="@Model.EndTime" class="form-control" />
                    </div>
                    <div class="mb-3">
                        <label class="form-label">Status :</label>
                        <div class="row">
                            <div class="col">
                                <div class="custom-control custom-radio">
                                    <input class="custom-control-input custom-control-input-success" asp-for="ActiveStatus" type="radio" id="customRadio1-@Model.Id" value="Active">
                                    <label for="customRadio1-@Model.Id" class="custom-control-label">Active</label>
                                </div>
                            </div>
                            <div class="col">
                                <div class="custom-control custom-radio">
                                    <input class="custom-control-input custom-control-input-danger" asp-for="ActiveStatus" type="radio" id="customRadio2-@Model.Id" value="Inactive">
                                    <label for="customRadio2-@Model.Id" class="custom-control-label">Inactive</label>
                                </div>
                            </div>
                            <div class="col-10"></div>
                        </div>

                    </div>
                    <div class="modal-footer">
                        <button type="submit" class="btn bg-gradient-info">Save changes</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>