MAMS/Controllers/DoctorController.cs
using AspNetCoreHero.ToastNotification.Abstractions;
using MAMS.Models;
using MAMS.Models.ViewModels;
using MAMS.Services;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;

namespace MAMS.Controllers
{
    public class DoctorController : BaseController
    {
        private readonly ILogger<DoctorController> _logger;
        public DoctorController(IConfiguration config, INotyfService notfy, ILogger<DoctorController> logger, IHttpContextAccessor contextAccessor, AppSettings appSettings) 
            : base(config, notfy, contextAccessor, appSettings)
        {
            _logger = logger;
        }

        public async Task<IActionResult> Index()
        {
            IList<DoctorDetailsViewModel> doctors = new List<DoctorDetailsViewModel>();

            if (!IsSessionValid())
            {
                return View("TimedOut", "Home");
            }

            try
            {
                var result = await _userService.GetDoctorsAsync();

                if (result.Item1 != null)
                {
                    doctors = result.Item1;
                }
                else
                {

                    _notfy.Error(result.Item2);
                    return View();
                }

                ViewData.Model = doctors;
            }
            catch (Exception ex)
            {
                ModelState.AddModelError(string.Empty, $"Error: {ex.Message}");
                _notfy.Warning($"{ex.Message}", 5);
            }
            return View();
        }

        public async Task<IActionResult> Profile(string userName)
        {
            DoctorDetailsViewModel doctor = new DoctorDetailsViewModel();

            if (!IsSessionValid())
            {
                return View("TimedOut", "Home");
            }

            try
            {
                var result = await _userService.GetDoctorDetailsAsync(userName);

                if (result.Item1 != null)
                {
                    doctor = result.Item1;
                }
                else
                {
                    _notfy.Error(result.Item2);
                    return View();
                }
                ViewData.Model = doctor;
            }
            catch (Exception ex)
            {
                ModelState.AddModelError(string.Empty, $"Error: {ex.Message}");
                _notfy.Warning($"{ex.Message}", 5);
            }
            return View();
        }

        public async Task<IActionResult> Edit(string Doctor)
        {
            DoctorDetailsViewModel doctorDetailsViewModel = new DoctorDetailsViewModel();

            if (!IsSessionValid())
            {
                return View("TimedOut", "Home");
            }

            try
            {
                var (activeSpecializations, errorMessage) = await _specializationService.GetAllSpecializationsAsync();

                ViewBag.Specializaions = activeSpecializations
                    .Where(s => s.Record_Status == Enums.ActiveStatus.Active)
                    .ToList();

                var result = await _userService.GetDoctorDetailsAsync(Doctor);

                if (result.Item1 != null)
                {
                    doctorDetailsViewModel = result.Item1;
                }
                else
                {
                    _notfy.Error(result.Item2);
                    return View();
                }
                ViewData.Model = doctorDetailsViewModel;
            }
            catch (Exception ex)
            {

                ModelState.AddModelError(string.Empty, $"Error: {ex.Message}");
                _notfy.Warning($"{ex.Message}", 5);
            }
            return View();
        }
    }
}

MAMS/Views/Doctor/Index.cshtml
@using System.Data
@using MAMS.Services
@using MAMS.Models.ViewModels

@{
    ViewData["Title"] = "Doctors";
}

@model IEnumerable<DoctorDetailsViewModel>

<div class="container">
    <div class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-12 d-flex justify-content-between align-items-center">
                    <h1>Doctors</h1>
                </div>
                <div class="col-sm-12">
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item"><a href="#">Admin</a></li>
                        <li class="breadcrumb-item active">All Doctors</li>
                    </ol>
                </div>
            </div><!-- /.row -->
        </div><!-- /.container-fluid -->
    </div>

    <div class="content">

            @if (Model == null)
            {
                <div class="alert alert-danger" role="alert">
                    Error: Failed to load data. Please try again later. or Please Log in again..
                </div>
            }
            else if (!Model.Any())
            {
                <div class="alert alert-info" role="alert">
                    No doctors found.
                </div>
            }
            else
            {
                <div class="row row-cols-2">
                    @foreach (var doctor in Model)
                    {
                        @await Html.PartialAsync("_DoctorCard", doctor)
                    }
                </div>
            }

    </div>

MAMS/Views/Doctor/Profile.cshtml
@model MAMS.Models.ViewModels.DoctorDetailsViewModel

@{
    ViewData["Title"] = "Profile";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container">
    <div class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-12 d-flex justify-content-between align-items-center">
                    <h1>Profile</h1>
                </div>
                <div class="col-sm-12">
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item"><a asp-action="Index">Doctors</a></li>
                        <li class="breadcrumb-item active">Profile View</li>
                    </ol>
                </div>
            </div><!-- /.row -->
        </div><!-- /.container-fluid -->
    </div>

    <div class="content">
        <div class="container-fluid">
            <div class="card card-info card-outline">
                <div class="card-header card-header d-flex justify-content-between align-items-center">
                    <div>
                        <h4 class="text-info"><b>@Model.UserTitle</b>&nbsp; @Model.First_Name @Model.Middle_Name @Model.Last_Name</h4>
                    </div>
                </div>

                <div class="card-body">
                    <table class="table table-hover table-striped">
                        <tr>
                            <th class="col-sm-2 ">Username</th>
                            <td class="col-sm-10">@Model.UserName</td>
                        </tr>

                        <tr>
                            <th class="col-sm-2">Email</th>
                            <td class="col-sm-10">@Model.Email</td>
                        </tr>
                        <tr>
                            <th class="col-sm-2 ">Phone Number</th>
                            <td class="col-sm-10">@Model.PhoneNumber</td>
                        </tr>

                        <tr>
                            <th class="col-sm-2">Address</th>
                            <td class="col-sm-10">@Model.Address, @Model.City, @Model.District, @Model.Province</td>
                        </tr>

                        <tr>
                            <th class="col-sm-2">Birth Date</th>
                            <td class="col-sm-10">@Model.Birth_Date.ToString("d")</td>
                        </tr>

                        <tr>
                            <th class="col-sm-2">Gender</th>
                            <td class="col-sm-10">@Model.Gender</td>
                        </tr>

                        <tr>
                            <th class="col-sm-2">Blood Type</th>
                            <td class="col-sm-10">@Model.Blood_Type</td>
                        </tr>

                        <tr>
                            <th class="col-sm-2">Personal ID</th>
                            <td class="col-sm-10">@Model.Personal_Id (@Model.PersonalId_Type)</td>
                        </tr>

                        <tr>
                            <th class="col-sm-2">Medical Council Registration Number</th>
                            <td class="col-sm-10">@Model.MedicalCouncilRegistrationNumber</td>
                        </tr>

                        <tr>
                            <th class="col-sm-2">Specialization</th>
                            <td class="col-sm-10">@Model.Specialization</td>
                        </tr>

                        <tr>
                            <th class="col-sm-2">Hospital Affiliation</th>
                            <td class="col-sm-10">@Model.Hospital_Affiliation</td>
                        </tr>
                        <tr>
                            <th class="col-sm-2">Doctor Fee</th>
                            <td class="col-sm-10">Rs @Model.Doctor_Fee</td>
                        </tr>
                    </table>
                </div>
                <div class="card-footer">
                    <a asp-action="Index" class="btn bg-gradient-secondary rounded-pill">
                        <i class="bi bi-backspace"></i> &nbsp; Back to List
                    </a> 
                    |
                    <a asp-action="Edit" asp-route-Doctor="@Model.UserName" class="btn bg-gradient-info rounded-pill">
                        <i class="bi bi-pencil-square"></i> &nbsp; Edit
                    </a> 
                    
                </div>
            </div>
        </div>
    </div>

</div>

MAMS/Views/Doctor/_DoctorCard.cshtml
@model MAMS.Models.ViewModels.DoctorDetailsViewModel

<div class="g-col-6">
    <div class="card card-info card-outline shadow">
        <div class="card-header text-muted border-bottom-0 card-outline">
        @Model.UserName
        <input asp-for="@Model.Id" hidden />
    </div>
    <div class="card-body pt-0">
        <div class="row">
            <div class="col-7">
                <h2 class="lead">@Model.UserTitle.  <b>@Model.First_Name</b> @Model.Last_Name</h2>
                <p class="text-muted text-sm"><b>Spec: </b> @Model.Specialization </p>
                <ul class="ml-4 mb-0 fa-ul text-muted">
                    <li class="small"><span class="fa-li"><i class="fas fa-lg fa-building"></i></span> Address: @Model.Address</li>
                    <li class="small"><span class="fa-li"><i class="fas fa-lg fa-phone"></i></span> Phone: @Model.PhoneNumber</li>
                </ul>
                @* <ul class="ml-4 mb-0 fa-ul text-muted">
                    <li class="small"><span class="fa-li"><i class="bi bi-calendar-check"></i></span> Ava: @Model.Email</li>
                    <li class="small"><span class="fa-li"><i class="bi bi-alarm-fill"></i></span> Time: @Model.Personal_Id</li>
                </ul> *@
            </div>
            <div class="col-5 text-center">
                <img src="~/adminlte/dist/img/user1-128x128.jpg" alt="user-avatar" class="img-circle img-fluid">
            </div>
        </div>
    </div>
    <div class="card-footer">
        <div class="text-right">
                <a asp-controller="Availability" asp-action="Index" asp-route-id="@Model.Id" class="btn btn-sm bg-gradient-teal">
                <i class="bi bi-calendar-check"></i> &nbsp; Availability
            </a>
                <a asp-controller="Doctor" asp-action="Profile" asp-route-userName="@Model.UserName" class="btn btn-sm bg-gradient-primary">
                <i class="fas fa-user"></i> View Profile
            </a>
        </div>
    </div>
    </div>
</div>