MAMS/Models/Specializations.cs
using System.ComponentModel.DataAnnotations;
using static MAMS.Services.Enums;

namespace MAMS.Models
{
    public class Specializations
    {
        [Key]
        public int Specializations_Id { get; set; }
        [Required]
        public string Specializations_Name { get; set; }
        public string? Description { get; set; }
        public ActiveStatus Record_Status { get; set; } = ActiveStatus.Active;
    }
}

MAMS/Controllers/SpecializationController.cs
using AspNetCoreHero.ToastNotification.Abstractions;
using MAMS.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using Newtonsoft.Json;
using System.Net.Http.Headers;
using System.Net;
using System.Net.Http.Json;
using MAMS.Services;

namespace MAMS.Controllers
{
    public class SpecializationController : BaseController
    {
        private readonly ILogger<SpecializationController> _logger;

        public SpecializationController(IConfiguration config, INotyfService notfy, ILogger<SpecializationController> logger, IHttpContextAccessor contextAccessor, AppSettings appSettings)
        : base(config, notfy, contextAccessor, appSettings)
        {
            _logger = logger;

        }

        public async Task<IActionResult> Index()
        {
            //calling the web API and populating the data in view using Entity Model Class

            IList<Specializations> dt = new List<Specializations>();

            if (!IsSessionValid())
            {
                return View("TimedOut", "Home");
            }

            try
            {
                var result = await _specializationService.GetAllSpecializationsAsync();


                if (result.Item1 != null)
                {
                    dt = result.Item1;
                }
                else
                {
                    _notfy.Error(result.Item2);
                    return View();
                }

                ViewData.Model = dt;
            }
            catch (Exception ex)
            {
                ModelState.AddModelError(string.Empty, $"Error: {ex.Message}");
                _notfy.Warning($"{ex.Message}", 5);
            }
            return View();
        }

        public async Task<IActionResult> Status()
        {
            if (!IsSessionValid())
            {
                return View("TimedOut", "Home");
            }

            return View();
        }

        public IActionResult Create()
        {
            if (!IsSessionValid())
            {
                return View("TimedOut", "Home");
            }


            return View();
        }

        public async Task<IActionResult> CreateNew(Specializations newSpec)
        {


            Specializations specializations = new Specializations()
            {
                Specializations_Name = newSpec.Specializations_Name,
                Description = newSpec.Description,
            };

            if (!IsSessionValid())
            {
                return View("TimedOut", "Home");
            }

            try
            {

                if (ModelState.IsValid && newSpec.Specializations_Name != null)
                {

                    (bool success, string errorMessage) = await _specializationService.AddSpecializationAsync(specializations);

                    if (success)
                    {
                        _notfy.Success($"{newSpec.Specializations_Name}, Successfully Added  as a new Specialization!. ");
                        return RedirectToAction("Index");
                    }
                    else
                    {
                        _notfy.Error("Creation Fail!", 5);
                        _notfy.Warning(errorMessage);
                        ModelState.AddModelError(string.Empty, errorMessage);
                        return View("Create");
                    }
                }

            }
            catch (Exception ex)
            {
                ModelState.AddModelError(string.Empty, $"Error: {ex.Message}");
                _notfy.Error($"Error calling web API: {ex.Message}", 5);
                return View("Create");
            }
            return View();
        }

        public async Task<IActionResult> Edit(int Id)
        {
            Specializations dt = new Specializations();

            if (!IsSessionValid())
            {
                return View("TimedOut", "Home");
            }

            try
            {
                var result = await _specializationService.GetSpecialization(Id);

                if (result.Item1 != null)
                {
                    dt = result.Item1;
                }
                else
                {
                    _notfy.Error(result.Item2);
                    return RedirectToAction("Index");
                }
                ViewData.Model = dt;
            }
            catch (Exception ex)
            {
                _notfy.Error($"Error calling service: {ex.Message}", 5);
                return RedirectToAction("Index");
            }
            return View();

        }

        public async Task<IActionResult> Update(Specializations currentSpec)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    (bool success, string errorMessage) = await _specializationService.UpdateSpecializationAsync(currentSpec);

                    if (success)
                    {
                        _notfy.Success($"{currentSpec.Specializations_Name}, Updated successfully.");
                        return RedirectToAction("Index");
                    }
                    else
                    {
                        _notfy.Warning(errorMessage);
                        _notfy.Error("update Fail!.", 5);
                        return View("Edit");
                    }
                }
            }
            catch (Exception ex)
            {
                ModelState.AddModelError(string.Empty, $"Error: {ex.Message}");
                _notfy.Error($"Error calling web API: {ex.Message}", 5);
                return View("Edit");
            }
            return View();
        }

        public async Task<IActionResult> UpdateRec(int Id, bool isChecked)
        {
            if (!IsSessionValid())
            {
                return View("TimedOut", "Home");
            }

            try
            {
                if (ModelState.IsValid)
                {
                    (bool success, string errorMessage) = await _specializationService.UpdateRecordStatusAsync(Id, isChecked);

                    if (success)
                    {
                        _notfy.Success($"Updated successfully.");
                        return RedirectToAction("Index");
                    }
                    else
                    {
                        _notfy.Warning(errorMessage);
                        _notfy.Error("update Fail!.", 5);
                        return View("Edit");
                    }
                }

            }
            catch (Exception ex)
            {
                ModelState.AddModelError(string.Empty, $"Error: {ex.Message}");
                _notfy.Error($"Error calling web API: {ex.Message}", 5);
                return RedirectToAction("Index");
            }
            return RedirectToAction("Index");
        }

        public async Task<IActionResult> Delete(int id)
        {
            try
            {
                var result = await _specializationService.DeleteRecordAsync(id);

                if (result.Success)
                {
                    _notfy.Success("Delete Successfully!");
                }
                else
                {
                    _notfy.Warning(result.ErrorMessage);
                    _notfy.Error("Deletion Fail!.", 5);
                }
            }
            catch (Exception ex)
            {
                _notfy.Error($"Error calling web API: {ex.Message}", 5);
            }
            return RedirectToAction("Index");
        }
    }
}

MAMS/Views/Specialization/Create.cshtml
@model Specializations

@{
    ViewData["Title"] = "Create Specialization";
}

<div class="container">
    <div class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-12 d-flex justify-content-between align-items-center">
                    <h1>New Specialization</h1>
                    <a asp-controller="Specialization" asp-action="Index" class="btn bg-gradient-secondary rounded-pill">
                        <i class="bi bi-backspace"></i> &nbsp; Back To List
                    </a>
                </div>
                <div class="col-sm-12">
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item"><a href="#">Specializations</a></li>
                        <li class="breadcrumb-item active">Create New</li>
                    </ol>
                </div>
            </div><!-- /.row -->
        </div><!-- /.container-fluid -->
    </div>
    <div class="content">
            <form asp-controller="Specialization" asp-action="CreateNew" method="post" id="CreateNew" novalidate>
                <div class="card card-success card-outline">
                    <div class="card-header">
                        <h5 class="m-0">Enter Details:</h5>
                    </div>

                    <div class="card-body">
                        <div class="mb-3">
                            <label asp-for="Specializations_Name" class="form-label">Specialization:</label>
                            <input asp-for="Specializations_Name" class="form-control" required />
                            <span asp-validation-for="Specializations_Name" class="text-danger"></span>
                        </div>

                        <div class="mb-3">
                            <label asp-for="Description" class="form-label">Description:</label>
                            <textarea asp-for="Description" class="form-control"></textarea>
                            <span asp-validation-for="Description" class="text-danger"></span>
                        </div>
                    </div>

                    <div class="card-footer">
                        <div class="text-end">
                            <button type="button" class="btn bg-gradient-success rounded-pill" style="width:150px" onclick="showConfirmationModal()" id="createButton">
                                <i class="bi bi-plus-circle"></i> &nbsp; Create
                            </button>
                        </div>
                    </div>

                </div>
            </form>
    </div>
</div>

<div class="modal fade" id="confirmationModal" tabindex="-1" role="dialog" aria-labelledby="confirmationModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-body">
                Are you sure you want to Create this?
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">No</button>
                <button type="button" class="btn btn-warning" id="confirmYes">Yes</button>
            </div>
        </div>
    </div>
</div>

@section Scripts {
    @{
        <partial name="_ValidationScriptspartial" />
    }
    <script>
        //Function to show the confirmation modal
        function showConfirmationModal() {
            $('#confirmationModal').modal('show');
        }

        // Handle form submission when "Yes" is clicked
        $('#confirmYes').click(function () {
            $('#confirmationModal').modal('hide'); // Hide the modal
            $('form').submit(); // Submit the form
        });

        // Attach the confirmation dialog to the Create button
        $(document).ready(function () {
            $('button[type="submit"]').click(function (e) {
                e.preventDefault(); // Prevent the default form submission
                showConfirmationModal(); // Show the confirmation modal
            });
        });

        document.addEventListener('DOMContentLoaded', function () {
            var createForm = document.getElementById('CreateNew');
            var createButton = document.getElementById('createButton');

            // Disable the button initially
            createButton.disabled = true;

            // Add an event listener to check form validity on input
            createForm.addEventListener('input', function () {
                createButton.disabled = !createForm.checkValidity();
            });

            // Add an event listener to handle form submission
            createForm.addEventListener('submit', function (event) {
                // Prevent the default form submission
                event.preventDefault();

                // Check form validity before allowing submission
                if (createForm.checkValidity()) {
                    // If the form is valid, you can enable the button and perform any other actions
                    createButton.disabled = false;
                    createButton.innerHTML = '<span class="spinner-border spinner-border-sm" role="status" aria-hidden="true"></span> Loading...';

                    // Optionally, you can trigger your confirmation modal or other actions here
                    showConfirmationModal();
                }
            });
        });

    </script>
}

MAMS/Views/Specialization/Edit.cshtml
@model Specializations

@{
    ViewData["Title"] = "Edit Specialization";
}

<div class="container">
    <div class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-12 d-flex justify-content-between align-items-center">
                    <h1>Edit Specialization</h1>
                    <a asp-controller="Specialization" asp-action="Index" class="btn bg-gradient-secondary rounded-pill">
                        <i class="bi bi-backspace"></i> &nbsp; Back To List
                    </a>
                </div>
                <div class="col-sm-12">
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item"><a href="#">Specializations</a></li>
                        <li class="breadcrumb-item active">update</li>
                    </ol>
                </div>
            </div><!-- /.row -->
        </div><!-- /.container-fluid -->
    </div>

    <div class="content">
        <div class="container-fluid">
            <div class="card card-info card-outline">
                <div class="card-header">
                    <h4 class="card-title text-info">Edit Details: </h4>
                </div>
                <form method="post" asp-action="Update">
                    <div class="card-body">
                        <input asp-for="Specializations_Id" hidden />
                        <div class="mb-3">
                            <label asp-for="Specializations_Name"></label>
                            <input asp-for="Specializations_Name" class="form-control" />
                            <span asp-validation-for="Specializations_Name" class="text-danger"></span>
                        </div>

                        <div class="mb-3">
                            <label asp-for="Description">Description</label>
                            <textarea asp-for="Description" class="form-control"></textarea>
                            <span asp-validation-for="Description" class="text-danger"></span>
                        </div>

                        @* <div class="mb-3">
                        <label asp-for="Record_Status">Status</label><br>
                        <div>
                        <input type="radio" asp-for="Record_Status" value="Active" /> Active
                        <input type="radio" asp-for="Record_Status" value="Inactive" /> Inactive
                        </div>
                        <span asp-validation-for="Record_Status" class="text-danger"></span>
                        </div> *@
                        <div class="mb-3">
                            <label class="form-label">Status :</label>
                            <div class="row">
                                <div class="col">
                                    <div class="custom-control custom-radio">
                                        <input class="custom-control-input custom-control-input-success" asp-for="Record_Status" type="radio" id="customRadio1" value="Active">
                                        <label for="customRadio1" class="custom-control-label">Active</label>
                                    </div>
                                </div>
                                <div class="col">
                                    <div class="custom-control custom-radio">
                                        <input class="custom-control-input custom-control-input-danger" asp-for="Record_Status" type="radio" id="customRadio2" value="Inactive">
                                        <label for="customRadio2" class="custom-control-label">Inactive</label>
                                    </div>
                                </div>
                                <div class="col-10"></div>
                            </div>

                        </div>
                    </div>
                    <div class="card-footer">
                        <button type="submit" class="btn bg-gradient-info rounded-pill float-right" style="width:150px"><i class="bi bi-arrow-clockwise" onclick=showConfirmationModal()></i> &nbsp; Update</button>
                        
                    </div>
                </form>
            </div>

        </div>
    </div>
</div>

<div class="modal fade" id="confirmationModal" tabindex="-1" role="dialog" aria-labelledby="confirmationModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-body">
                Are you sure you want to Update/Modify this Specialization?
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">No</button>
                <button type="button" class="btn btn-warning" id="confirmYes">Yes</button>
            </div>
        </div>
    </div>
</div>

@section Scripts {
    @{
        <partial name="_ValidationScriptspartial" />
    }
    <script>
        //Function to show the confirmation modal
        function showConfirmationModal() {
            $('#confirmationModal').modal('show');
        }

        // Handle form submission when "Yes" is clicked
        $('#confirmYes').click(function () {
            $('#confirmationModal').modal('hide'); // Hide the modal
            $('form').submit(); // Submit the form
        });

        // Attach the confirmation dialog to the Create button
        $(document).ready(function () {
            $('button[type="submit"]').click(function (e) {
                e.preventDefault(); // Prevent the default form submission
                showConfirmationModal(); // Show the confirmation modal
            });
        });
    </script>
}

MAMS/Views/Specialization/Index.cshtml
@using System.Data
@using MAMS.Services
@{
    ViewData["Title"] = "Specializations";
}
@model IEnumerable<Specializations>

<div class="container">
    <div class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-12 d-flex justify-content-between align-items-center">
                    <h1>Specializations</h1>
                    <a asp-controller="Specialization" asp-action="Create" class="btn bg-gradient-warning rounded-pill">
                        <i class="bi bi-plus-circle"></i> Create New
                    </a>
                </div>
                <div class="col-sm-12">
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item"><a href="#">Admin</a></li>
                        <li class="breadcrumb-item active">All Specializations</li>
                    </ol>
                </div>
            </div><!-- /.row -->
        </div><!-- /.container-fluid -->
    </div>
    <div class="content">
        <div class="row">
            <div class="col-12">
                <div class="card card-info card-outline">
                    <div class="card-header d-flex justify-content-between align-items-center">
                        <form method="get" asp-controller="Specialization" asp-action="Index" class="d-flex ml-auto">
                            <div class="input-group input-group-sm" style="width: 250px;">
                                <input type="text" name="searchString" class="form-control float-left" placeholder="Search by specialization or status" value="@ViewData["CurrentFilter"]">
                                <div class="input-group-append">
                                    <button type="submit" class="btn btn-default">
                                        <i class="fas fa-search"></i>
                                    </button>
                                </div>
                            </div>
                        </form>
                    </div>
                    <!-- /.card-header -->
                    <div class="card-body table-responsive p-0">
                        <table class="table table-hover">
                            <thead>
                                <tr>
                                    <th>Specialization</th>
                                    <th class="text-center">Description</th>
                                    <th>Status</th>
                                    <th>Actions</th>
                                </tr>
                            </thead>
                            <tbody>
                                @if (Model == null)
                                {
                                    <tr>
                                        <td colspan="4">
                                            <div class="alert alert-danger text-center" role="alert">
                                                Error: Failed to load data. Please try again later or log in again.
                                            </div>
                                        </td>
                                    </tr>
                                }
                                else
                                {
                                    @foreach (var obj in Model)
                                    {
                                        <tr>
                                            <input asp-for="@obj.Specializations_Id" hidden />
                                            <td data-Specializations_Name="@obj.Specializations_Name">@obj.Specializations_Name</td>
                                            <td class="text-start text-break">@obj.Description</td>
                                            <td class="text-center">
                                                @if (obj.Record_Status == Enums.ActiveStatus.Active)
                                                {
                                                    <span class="badge bg-gradient-success">Active</span>
                                                }
                                                else if (obj.Record_Status == Enums.ActiveStatus.Inactive)
                                                {
                                                    <span class="badge bg-gradient-danger">Inactive</span>
                                                }
                                            </td>
                                            <td>
                                                <div class="btn-group" role="group">
                                                    <a asp-controller="Specialization" asp-action="Edit" asp-route-id="@obj.Specializations_Id" class="btn btn-light" title="Edit">
                                                        <i class="bi bi-pencil-square"></i>
                                                    </a>
                                                    <a href="#" class="delete-button btn btn-light" data-id="@obj.Specializations_Id" title="Delete">
                                                        <i class="bi bi-trash3-fill"></i>
                                                    </a>
                                                </div>
                                            </td>
                                        </tr>
                                    }
                                }
                            </tbody>
                        </table>
                    </div>
                    <!-- /.card-body -->
                </div>
                <!-- /.card -->
            </div>
        </div>
    </div>
</div>

<div class="modal fade" id="deleteConfirmationModal" tabindex="-1" role="dialog" aria-labelledby="showDeleteConfirmationModal" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-body">
                Are you sure you want to Delete this Specialization?
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">No</button>
                <button type="button" class="btn btn-danger" id="confirmYes" data-id="">Yes</button>
            </div>
        </div>
    </div>
</div>

@section scripts {
    <script>
        $(document).ready(function () {
            // Handle checkbox toggle event
            $('.status-switch').change(function () {
                var specializationId = $(this).data('specializations-id');
                var isChecked = $(this).prop('checked');
                console.log(specializationId);
                console.log(isChecked);
                updateRecordStatus(specializationId, isChecked);
            });

            // Function to update Record_Status asynchronously
            function updateRecordStatus(specializationId, isChecked) {
                var apiUrl = '@Url.Action("UpdateRec", "Specialization")';

                $.ajax({
                    url: apiUrl,
                    type: 'POST', // or 'PUT' depending on your API
                    data: {
                        Id: specializationId,
                        isChecked: isChecked
                    },
                    success: function (result) {
                        // Handle success, if needed
                    },
                    error: function (error) {
                        console.error('Error updating Record_Status:', error);
                        // Handle error, if needed
                    }
                });
            }
        });
    </script>

    @{
        <partial name="_ValidationScriptspartial" />
    }
    <script>
        //Function to show the delete confirmation modal
        function showDeleteConfirmationModal(id) {
            $('#deleteConfirmationModal').modal('show');
            var id = $('#confirmYes').data('id', id);
        }

        // Attach the delete confirmation dialog to the Delete button
        $(document).ready(function () {
            $('.delete-button').click(function (e) {
                e.preventDefault(); // Prevent the default link behavior
                // Extract the id from the delete button's data-id attribute
                var id = $(this).data('id');
                showDeleteConfirmationModal(id); // Show the delete confirmation modal
            });

            // Handle form submission when "Yes" is clicked
            $('#confirmYes').click(function () {
                var id = $(this).data('id');
                $('#deleteConfirmationModal').modal('hide'); // Hide the modal
                // Redirect to the delete action with the id parameter
                console.log("Deletion ID:", id);
                window.location.href = '@Url.Action("Delete", "Specialization")' + '?id=' + id;
            });
        });
    </script>
}