MAMS/Models/Appointments.cs
using System.ComponentModel.DataAnnotations;
using static MAMS.Services.Enums;

namespace MAMS.Models
{
    public class Appointments
    {
        [Key]
        public int Id { get; set; }
        [Required]
        public string User_PersonalId { get; set; }
        [Required]
        public int Doctor_Id { get; set; }
        public DateTime Appoinment_Date { get; set; }
        public ActiveStatus Status { get; set; } = ActiveStatus.Active;

        public UserDetails UserDetails { get; set; }
        public DoctorDetails DoctorDetails { get; set; }
        public Transactions Transactions { get; set; }
    }
}

MAMS/Models/ViewModels/BookingViewModel.cs
using System.ComponentModel.DataAnnotations;
using static MAMS.Services.Enums;

namespace MAMS.Models.ViewModels
{
    public class BookingViewModel
    {
        public string UserTitle { get; set; }
        public string Name { get; set; }
        public string? Email { get; set; }
        public string PhoneNumber { get; set; }
        public string PersonalId_Type { get; set; }
        public string Personal_Id { get; set; }
        public string? Address { get; set; }
        public string? City { get; set; }
        public DateTime? BirthDate { get; set; }
        public int Availability_Id { get; set; }
        public int Doctor_Id { get; set; }
        public string Available_Day { get; set; }
        public DateTime Appointment_Date { get; set; }
        public int Appoinment_number { get; set; }
        public TimeSpan? StartTime { get; set; }
        public TimeSpan? EndTime { get; set; }
        public decimal Doctor_fee { get; set; }
        public decimal Hospital_fee { get; set; }
        public decimal Discount { get; set; } = 0;
        public decimal Amount { get; set; }
        public PaymentMethod PaymentMethod { get; set; }
    }
}

MAMS/Controllers/AppointmentController.cs
using AspNetCoreHero.ToastNotification.Abstractions;
using MAMS.Models;
using MAMS.Models.ViewModels;
using MAMS.Services;
using Microsoft.AspNetCore.Mvc;

namespace MAMS.Controllers
{
    public class AppointmentController : BaseController
    {
        private readonly ILogger<DoctorController> _logger;

        public AppointmentController(IConfiguration config, INotyfService notfy, ILogger<DoctorController> logger, IHttpContextAccessor contextAccessor, AppSettings appSettings)
            : base(config, notfy, contextAccessor, appSettings)
        {
            _logger = logger;
        }

        public async Task<IActionResult> Index()
        {
            IList<DoctorAvailabilityViewModel> doctors = new List<DoctorAvailabilityViewModel>();

            if (!IsSessionValid())
            {
                return View("TimedOut", "Home");
            }

            try
            {
                var result = await _appointmentService.GetDoctorsAll();

                if (result.Item1 != null)
                {
                    doctors = result.Item1;
                }
                else
                {
                    _notfy.Error(result.Item2);
                    return View();
                }
                ViewData.Model = doctors;
            }

            catch (Exception ex)
            {
                ModelState.AddModelError(string.Empty, $"Error: {ex.Message}");
                _notfy.Warning($"{ex.Message}", 5);
            }
            return View();
        }

        public async Task<IActionResult> Search()
        {
            var (activeSpecializations, errorMessage) = await _specializationService.GetAllSpecializationsAsync();

            ViewBag.Specializaions = activeSpecializations
                .Where(s => s.Record_Status == Enums.ActiveStatus.Active)
                .ToList();

            return View();
        }

        public async Task<IActionResult> SearchDoctors(string? name, string? specialization)
        {
            var (activeSpecializations, errorMessage) = await _specializationService.GetAllSpecializationsAsync();

            ViewBag.Specializaions = activeSpecializations
                .Where(s => s.Record_Status == Enums.ActiveStatus.Active)
                .ToList();

            IList<DoctorDetails> doctors = new List<DoctorDetails>();

            if (!IsSessionValid())
            {
                return View("TimedOut", "Home");
            }

            try
            {
                var results = await _appointmentService.GetDoctorByName(name, specialization);

                if (results.Item1 != null)
                {
                    doctors = results.Item1;
                }
                else
                {
                    _notfy.Error(results.Item2);
                    return View("Search");
                }
                ViewData.Model = doctors;
            }

            catch (Exception ex)
            {
                ModelState.AddModelError(string.Empty, $"Error: {ex.Message}");
                _notfy.Warning($"{ex.Message}", 5);
            }
            return View("Search");
        }

        public async Task<IActionResult> Availabilities(int Id)
        {
            IList<DoctorAvailableDetails> doctors = new List<DoctorAvailableDetails>();

            if (!IsSessionValid())
            {
                return View("TimedOut", "Home");
            }

            try
            {
                var result = await _availabilityService.AvailabilityAsync(Id);

                if (result.Item1 != null)
                {
                    doctors = result.Item1.Where(s => s.ActiveStatus == Enums.ActiveStatus.Active).ToList();
                }
                else
                {
                    _notfy.Error(result.Item2);
                    return View();
                }
                ViewData.Model = doctors;
            }

            catch (Exception ex)
            {
                ModelState.AddModelError(string.Empty, $"Error: {ex.Message}");
                _notfy.Warning($"{ex.Message}", 5);
            }
            return View();
        }

        public async Task<IActionResult> Booking(int Id, int DoctorId)
        {
            try
            {
                var (availability, errorMessage1) = await _availabilityService.GetAvailability(Id);

                if (availability == null)
                {
                    _notfy.Error("Availability Not Found!");
                    return View();
                }

                if (!Enum.TryParse(availability.Available_Day, true, out DayOfWeek dayOfWeek))
                {
                    _notfy.Error("Invalid Day of the Week!");
                    return View();
                }

                DateTime date = _calanderService.GetDateForDayOfWeek(dayOfWeek);
                var lastAppointmentNumber = await _appointmentService.GetLastAppointmentNumberAsync(Id, date);
                var yourAppointmentNumber = lastAppointmentNumber + 1;

                var appointmentCount = await _appointmentService.GetAppointmentCountAsync(Id, date);

                var doctorDetails = await _userService.GetDoctorDetailsByIdAsync(DoctorId);

                ViewBag.appointmentDate = date;
                ViewBag.YourAppointmentNumber = yourAppointmentNumber;
                ViewBag.AppointmentCount = appointmentCount;

                var doctorFee = doctorDetails.Item1.Doctor_Fee;
                var hospitalFee = doctorFee * 0.30m;
                var total = doctorFee + hospitalFee;

                ViewBag.doctorFee = doctorFee;
                ViewBag.hospitalFee = hospitalFee.ToString("F2");
                ViewBag.totalFee = total.ToString("F2");


                string? user = HttpContext.Session.GetString("UserName");

                if (user == null)
                {
                    _notfy.Warning("Please Log In.");
                    return View();
                }

                var (userDetails, errorMessage2) = await _userService.GetUserDetailsAsync(user);

                if (userDetails == null)
                {
                    _notfy.Error("user Details Not Found!");
                    return View();
                }

                var viewModel = new BookingViewModel
                {
                    UserTitle = userDetails.UserTitle,
                    Name = userDetails.First_Name + ' ' + userDetails.Last_Name,
                    Email = userDetails.Email,
                    PhoneNumber = userDetails.PhoneNumber,
                    PersonalId_Type = userDetails.PersonalId_Type,
                    Personal_Id = userDetails.Personal_Id,
                    Doctor_Id = availability.DoctorId,
                    Availability_Id = availability.Id,
                    Available_Day = availability.Available_Day,
                    Appointment_Date = date,
                    Appoinment_number = yourAppointmentNumber,
                    StartTime = availability.StartTime,
                    EndTime = availability.EndTime,
                    Doctor_fee = doctorFee,
                    Hospital_fee = hospitalFee,
                    Amount = total
                };

                return View(viewModel);
            }

            catch (Exception ex)
            {
                ModelState.AddModelError(string.Empty, $"Error: {ex.Message}");
                _notfy.Warning($"{ex.Message}", 5);
            }

            return View();
        }

        public async Task<IActionResult> PlaceNewAppointment(BookingViewModel bookingViewModel)
        {
            try
            {
                (bool success, string errorMessage) = await _appointmentService.AddAppointmentAsync(bookingViewModel);

                if (success)
                {
                    _notfy.Success($"Appointment Placed! - Appointment number :{bookingViewModel.Appoinment_number} - Appointment Date : {bookingViewModel.Appointment_Date} ");
                    return RedirectToAction("Search");
                }
                else
                {
                    await Booking(bookingViewModel.Availability_Id, bookingViewModel.Doctor_Id);
                    _notfy.Error(errorMessage, 5);
                    return View("Booking");
                }

            }
            catch (Exception ex)
            {
                await Booking(bookingViewModel.Availability_Id, bookingViewModel.Doctor_Id);
                ModelState.AddModelError(string.Empty, $"Error: {ex.Message}");
                _notfy.Error($"Error calling web API: {ex.Message}", 5);
                return View("Booking");
            }
        }
    }




}

MAMS/Views/Appointment/Availabilities.cshtml
@using MAMS.Models.ViewModels


@{
    ViewData["Title"] = "Availabilities";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@model IEnumerable<DoctorAvailableDetails>

<link rel="stylesheet" href="~/adminlte/plugins/datatables-bs4/css/dataTables.bootstrap4.min.css">
<link rel="stylesheet" href="~/adminlte/plugins/datatables-responsive/css/responsive.bootstrap4.min.css">
<link rel="stylesheet" href="~/adminlte/plugins/datatables-buttons/css/buttons.bootstrap4.min.css">

<div class="container">
    <div class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-12 d-flex justify-content-between align-items-center">
                    <h1>New Appointment</h1>

                </div>
                <div class="col-sm-12">
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item"><a asp-action="Index">Appointments</a></li>
                        <li class="breadcrumb-item active">Make New</li>
                    </ol>
                </div>
            </div>
        </div>
    </div>

    <div class="content">
        <div class="container-fluid">
            <div class="card card-info card-outline">
                <div class="card-header card-header d-flex justify-content-between align-items-center">
                </div>
                <!-- /.card-header -->

                <div class="card-body table-responsive p-0">

                    @if (Model == null)
                    {
                        <div class="alert alert-danger" role="alert">
                            Error: Failed to load data. Please try again later. or Please Log in again.
                        </div>
                    }
                    else if (!Model.Any())
                    {
                        <div class="alert alert-warning" role="alert">
                            NO Availability Found!
                        </div>
                    }

                    else
                    {
                        <table id="Availability" class="table table-hover">
                            <thead>
                                <tr>
                                    <th>Available Day</th>
                                    <th>From</th>
                                    <th>To</th>
                                    <th class="text-center">Actions</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach (var obj in Model)
                                {
                                    <tr>
                                        <input asp-for="@obj.Id" hidden />
                                        <input asp-for="@obj.DoctorId" hidden />
                                        <td data-Available_day="@obj.Available_Day">@obj.Available_Day</td>
                                        <td class="text-start">@(obj.StartTime.HasValue ? new DateTime(obj.StartTime.Value.Ticks).ToString("hh:mm tt") : "")</td>
                                        <td class="text-Start">@(obj.EndTime.HasValue ? new DateTime(obj.EndTime.Value.Ticks).ToString("hh:mm tt") : "")</td>


                                        <td class="text-center">
                                            <div class="btn-group btn-group-justified" role="group">
                                                <a asp-action="Booking" asp-route-id="@obj.Id" asp-route-doctorId="@obj.DoctorId" class="btn btn-primary btn-block"><b>Book</b></a>
                                            </div>
                                        </td>
                                    </tr>

                                }
                            </tbody>
                        </table>

                    }

                </div>
                <!-- /.card-body -->

                <div class="card-footer">
                    <a asp-controller="Appointment" asp-action="Search" class="btn bg-gradient-secondary rounded-pill float-right" style="width:150px"><i class="bi bi-backspace"></i> &nbsp; Back</a>
                </div>
            </div>
        </div>
    </div>



</div>

MAMS/Views/Appointment/Edit.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

MAMS/Views/Appointment/Index.cshtml
@using System.Data
@using MAMS.Services
@using MAMS.Models.ViewModels

@{
    ViewData["Title"] = "Availabilities";
    var doctorId = ViewData["DoctorId"] as int?;
}

@model IList<DoctorAvailabilityViewModel>

<!-- DataTables -->
<link rel="stylesheet" href="~/adminlte/plugins/datatables-bs4/css/dataTables.bootstrap4.min.css">
<link rel="stylesheet" href="~/adminlte/plugins/datatables-responsive/css/responsive.bootstrap4.min.css">
<link rel="stylesheet" href="~/adminlte/plugins/datatables-buttons/css/buttons.bootstrap4.min.css">

<div class="container">
    <div class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-12 d-flex justify-content-between align-items-center">
                    <h1>All Availabilities</h1>
                    <a asp-controller="Appointment" asp-action="Index" class="btn bg-gradient-secondary rounded-pill float-right" style="width:150px"><i class="bi bi-backspace"></i> &nbsp; Back</a>
                </div>
                <div class="col-sm-12">
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item"><a asp-action="Index">Appointments</a></li>
                        <li class="breadcrumb-item active">All Availabilities</li>
                    </ol>
                </div>
            </div><!-- /.row -->
        </div><!-- /.container-fluid -->
    </div>

    <div class="content">
        <div class="row">
            <div class="col-12">
                <div class="card card-info card-outline">
                    <div class="card-header card-header d-flex justify-content-between align-items-center">
                        <form method="get" asp-controller="Appointment" asp-action="Index" class="d-flex ml-auto">
                            <div class="input-group input-group-sm" style="width: 250px;">
                                <input type="text" name="searchString" class="form-control float-left" placeholder="Search by Day or Time" value="@ViewData["CurrentFilter"]">
                                <div class="input-group-append">
                                    <button type="submit" class="btn btn-default">
                                        <i class="fas fa-search"></i>
                                    </button>
                                </div>
                            </div>
                        </form>
                    </div>
                    <!-- /.card-header -->

                    <div class="card-body table-responsive p-0">

                        @if (Model == null)
                        {
                            <div class="alert alert-danger" role="alert">
                                Error: Failed to load data. Please try again later. or Please Log in again.
                            </div>
                        }
                        else if (!Model.Any())
                        {
                            <div class="alert alert-warning" role="alert">
                                NO Availability Found!
                            </div>
                        }

                        else
                        {
                            <table id="Availability" class="table table-hover">
                                <thead>
                                    <tr>
                                        <th>Doctor</th>
                                        <th>Specialization</th>
                                        <th>Available Day</th>
                                        <th>From</th>
                                        <th>To</th>
                                        <th>Status</th>
                                        @* <th class="text-center">Actions</th> *@
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach (var obj in Model)
                                    {
                                        <tr>
                                            <td class="text-Start" data-doctor>@obj.First_Name @obj.Last_Name</td>
                                            <td class="text-Start" data-specialization>@obj.Specialization</td>
                                            <td data-Available_day="@obj.Available_Day">@obj.Available_Day</td>
                                            <td class="text-start">@(obj.StartTime.HasValue ? new DateTime(obj.StartTime.Value.Ticks).ToString("hh:mm tt") : "")</td>
                                            <td class="text-start">@(obj.EndTime.HasValue ? new DateTime(obj.EndTime.Value.Ticks).ToString("hh:mm tt") : "")</td>
                                            <td class="text-center">
                                                @if (obj.ActiveStatus == Enums.ActiveStatus.Active)
                                                {
                                                    <span class="badge bg-gradient-success">Active</span>
                                                }
                                                else if (obj.ActiveStatus == Enums.ActiveStatus.Inactive)
                                                {
                                                    <span class="badge bg-gradient-danger">Inactive</span>
                                                }
                                            </td>

                                            @* <td class="text-center">
                                                <div class="btn-group btn-group-justified" role="group">
                                                    <button type="button" class="btn btn-light" data-bs-toggle="modal" data-bs-target="#editModal-@obj.Id" title="Edit">
                                                        <i class="bi bi-pencil-square"></i>
                                                    </button>
                                                    <button type="button" class="delete-button btn btn-light" data-id="@obj.Id" data-doctor-id="@obj.DoctorId" title="Delete">
                                                        <i class="bi bi-trash3-fill"></i>
                                                    </button>
                                                </div>
                                            </td> *@
                                        </tr>

                                        @* @await Html.PartialAsync("_EditAvailability", obj) *@

                                    }
                                </tbody>
                            </table>

                        }

                    </div>
                    <!-- /.card-body -->

                    <div class="card-footer">
                        <button type="button" class="btn bg-gradient-success rounded-pill float-right" data-bs-toggle="modal" data-bs-target="#addNewModal" data-doctor-id="@doctorId" style="width:150px">
                            <i class="bi bi-plus-circle"></i>&ensp; Add New
                        </button>
                    </div>
                </div>
                <!-- /.card -->
            </div>
        </div>
    </div>
</div>

MAMS/Views/Appointment/Search.cshtml
@using System.Data
@using MAMS.Services
@using MAMS.Models.ViewModels
@using static MAMS.Services.Enums

@{
    ViewData["Title"] = "Search";
    // var doctorId = ViewData["DoctorId"] as int?;
}

@model IEnumerable<DoctorDetails>

<div class="container">
    <div class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-12 d-flex justify-content-between align-items-center">
                    <h1>New Appointment</h1>
                </div>
                <div class="col-sm-12">
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item"><a asp-action="Index">Appointments</a></li>
                        <li class="breadcrumb-item active">Search</li>
                    </ol>
                </div>
            </div><!-- /.row -->
        </div><!-- /.container-fluid -->
    </div>

    <div class="content">
        <div class="container-fluid">

            <div class="info-box shadow">
                <span class="info-box-icon bg-olive"><i class="bi bi-search"></i></span>

                <div class="info-box-content">
                    <form method="get" asp-action="SearchDoctors" class="row g-3">
                        <div class="form-group col">
                            <input type="text" class="form-control rounded-pill" id="Name" name="name" placeholder="Enter doctor's name">
                        </div>
                        <div class="form-group col">
                            <select id="Specialization" name="Specialization" class="form-select rounded-pill">
                                <option value="">--Select Specialization--</option>
                                @foreach (var specializations in ViewBag.Specializaions)
                                {
                                    <option value="@specializations.Specializations_Name">@specializations.Specializations_Name</option>
                                }
                            </select>
                        </div>
                        <div class="col-2 text-center">
                            <button type="submit" class="btn btn-primary rounded-pill">Search</button>
                        </div>
                    </form>
                </div>
            </div>

            
            @if (Model != null && Model.Any())
            {
                <div class="row row-cols-4">
                    @foreach (var doctor in Model)
                    {
                        @await Html.PartialAsync("_DoctorProfile", doctor)
                    }
                </div>
            }
            else if (Model != null)
            {
                <div class="alert alert-info" role="alert">
                    No doctors found.
                </div>
            }
        </div>
    </div>
</div>

MAMS/Views/Appointment/_DoctorProfile.cshtml
@model MAMS.Models.DoctorDetails

<div class="g-col-6">
    <div class="card card-primary card-outline">
        <div class="card-body box-profile">
            <div class="text-center">
                <img class="profile-user-img img-fluid img-circle"
                     src="~/img/Doctor.png"
                     alt="User profile picture">
                <input asp-for="@Model.SuserId" hidden />
                <input asp-for="@Model.Id" hidden />
            </div>

            <h3 class="profile-username text-center">@Model.First_Name @Model.Last_Name</h3>

            <p class="text-muted text-center">@Model.Specialization</p>

            @* <ul class="list-group list-group-unbordered mb-3">
                <li class="list-group-item">
                    <b>Followers</b> <a class="float-right">1,322</a>
                </li>
                <li class="list-group-item">
                    <b>Following</b> <a class="float-right">543</a>
                </li>
                <li class="list-group-item">
                    <b>Friends</b> <a class="float-right">13,287</a>
                </li>
            </ul> *@

            <a asp-action="Availabilities" asp-route-id="@Model.Id" class="btn btn-primary btn-block"><b>Book Appointment</b></a>
        </div>
        <!-- /.card-body -->
    </div>
</div>